version: '3'
services:
    client:
      build: ./client/.
      container_name: client
      networks:
        client-connection:
          aliases:
            - client

    p1:
      build: ./m1/.
      volumes:
       - ./m1/conf:/etc/squid
      networks:
        internet-connection:
          aliases:
            - p1
      container_name: p1

    p2:
      build: ./m2/.
      volumes:
        - ./m2/conf:/etc/squid
      networks:
        proxy-network-1:
          aliases:
            - p2
        internet-connection:
          aliases:
            - p2
      container_name: p2

    p3:
      build: ./m3/.
      volumes:
       - ./m3/conf:/etc/squid
      networks:
        client-connection:
          aliases:
            - p3
        proxy-network-1:
          aliases:
            - p3
      container_name: p3

networks:
  client-connection:
    driver: overlay
    internal: true
  proxy-network-1:
    driver: overlay
    internal: true
  internet-connection: